### ISSUE TITLE
can't build on macOS 13.4 

### ISSUE THREAD

**Issue by SKforever6907** [named-data-ndnSIM/ndnSIM#116]
the latest ndnsim(2.9) can't build on macOS 13.4(compiler clang14.0.0)
src/internet/bindings/ns3module.cc:149967:39: error: expression is not assignable
    Py_TYPE(&PyNs3ArpL3Protocol_Type) = &PyNs3ArpL3ProtocolMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150011:30: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv4_Type) = &PyNs3Ipv4Meta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150036:40: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv4L3Protocol_Type) = &PyNs3Ipv4L3ProtocolMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150054:44: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv4MulticastRoute_Type) = &PyNs3Ipv4MulticastRouteMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150114:30: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv6_Type) = &PyNs3Ipv6Meta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150139:41: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv6ExtensionAH_Type) = &PyNs3Ipv6ExtensionAHMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150170:50: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv6ExtensionDestination_Type) = &PyNs3Ipv6ExtensionDestinationMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150199:42: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv6ExtensionESP_Type) = &PyNs3Ipv6ExtensionESPMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150223:47: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv6ExtensionFragment_Type) = &PyNs3Ipv6ExtensionFragmentMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150247:47: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv6ExtensionHopByHop_Type) = &PyNs3Ipv6ExtensionHopByHopMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150271:46: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv6ExtensionRouting_Type) = &PyNs3Ipv6ExtensionRoutingMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150303:40: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv6L3Protocol_Type) = &PyNs3Ipv6L3ProtocolMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150321:44: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv6MulticastRoute_Type) = &PyNs3Ipv6MulticastRouteMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150346:45: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv6OptionJumbogram_Type) = &PyNs3Ipv6OptionJumbogramMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150364:40: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv6OptionPad1_Type) = &PyNs3Ipv6OptionPad1Meta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150382:40: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv6OptionPadn_Type) = &PyNs3Ipv6OptionPadnMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150400:47: error: expression is not assignable
    Py_TYPE(&PyNs3Ipv6OptionRouterAlert_Type) = &PyNs3Ipv6OptionRouterAlertMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150460:36: error: expression is not assignable
    Py_TYPE(&PyNs3NdiscCache_Type) = &PyNs3NdiscCacheMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/internet/bindings/ns3module.cc:150498:32: error: expression is not assignable
    Py_TYPE(&PyNs3TcpBbr_Type) = &PyNs3TcpBbrMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

src/lte/bindings/ns3module.cc:200670:34: error: expression is not assignable
    Py_TYPE(&PyNs3EpcX2Sap_Type) = &PyNs3EpcX2SapMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/lte/bindings/ns3module.cc:201269:35: error: expression is not assignable
    Py_TYPE(&PyNs3LteRrcSap_Type) = &PyNs3LteRrcSapMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
src/lte/bindings/ns3module.cc:202657:33: error: expression is not assignable
    Py_TYPE(&PyNs3LtePdcp_Type) = &PyNs3LtePdcpMeta_Type;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
3 errors generated.
